#spring.application.name=BankProject
#spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
#spring.jpa.properties.hibernate.default_schema=users
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.com.bank=DEBUG
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.driver-class-name=org.postgresql.Driver


server:
  port: 8080
  servlet:
    context-path: /bank-api

spring:
  application:
    name: bank-registration-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Baku

jwt:
  secret: YourSuperSecretKeyForJWTTokenGenerationMinimum256Bits
  expiration:
    session: 300000      # 5 d?qiq?
    verification: 600000 # 10 d?qiq?
    access: 3600000      # 1 saat (Login)
    refresh: 604800000   # 7 g√ºn (Login)


logging:
  level:
    com.bank.registration: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html